# # Generated by Selenium IDE
# import pytest
# import time
# import json
# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
#
#
# class TestDefaultSuite():
#     def setup_method(self, method):
#         self.driver = webdriver.Chrome()
#         self.vars = {}
#
#     def teardown_method(self, method):
#         self.driver.quit()
#
#     def test_21(self):
#         self.driver.get("http://advertisement.dev.q1op.com/#/ad/audience")
#         self.driver.set_window_size(2064, 1128)
#         self.driver.find_element(By.CSS_SELECTOR, ".el-range-input:nth-child(2)").click()
#         self.driver.find_element(By.CSS_SELECTOR, ".el-range-input:nth-child(2)").send_keys("2020-01-01")
#         self.driver.close()
#         self.driver.find_element(By.CSS_SELECTOR, ".el-range-input:nth-child(4)").send_keys("2020-01-30")
#         self.driver.find_element(By.CSS_SELECTOR, ".el-range-input:nth-child(4)").send_keys(Keys.ENTER)
#


import time


def time_consuming(func):
    def test(*args, **kwargs):
        a = time.time()
        func = func(*args, **kwargs)
        b = time.time()
        maketime = round(a - b, 2)
        print('time:%ds' % maketime)
        return func

    return test
